first base project
Janee/sismomx-banco-tiempo pull request #4
Opened 2017-09-23 00:57 UTC by RegulEsteban

2017-09-23 02:57 UTC, Janee requested changes
Hay que añadir rspec para pruebas y eliminar los archivos de tests. Duda ¿El modelo eventos para que será? Notificaciones?

2017-09-23 02:57 UTC, Janee commented on Gemfile
> +  gem 'selenium-webdriver'
Falta añadir rspec para testing :)

2017-09-23 02:58 UTC, AlfonsoIMa approved these changes
Yo no le veo problema alguno, con excepción del SQLite3 y PostgreSQL, esperando segunda aprobación.

2017-09-23 04:53 UTC, RegulEsteban commented on Gemfile
> +  gem 'selenium-webdriver'
Ya está! :+1:

2017-09-23 14:02 UTC, Janee approved these changes
Listón azul.

2017-09-23 14:02 UTC, merged

2017-09-24 02:45 UTC, Janee commented
Issues #10 y #11